#0x05 Python - Exceptions
This is a Holberton School project working on Exceptions in Python.
###Goals of Project:
- Difference between errors & exceptions
- What are exceptions/how to use them
- When using exceptions is needed
- How to handle exceptions correctly
- Purpose of catchin exceptions
- How to raise a builtin exception
- When a clean-up action after an exception is necessary

##Files & Contents
- <b>0-safe_print_list.py</b>: Print a list up to a given index. If the index is greater than the length of the list catch the exception and print the whole list still.
- <b>1-safe_print_integer.py</b>: Print the given value if it's an integer using "{:d}".format(value). If the given value is not an integer catch the exception and return False.
- <b>2-safe_print_list_integers.py</b>: Print out all the integers in a given list up to a given index. If item in list is not integer catch the exception and continue to finish printing the list.
- <b>3-safe_print_division.py</b>: Print out the result of the division of two given integers. Catch the ZeroDivisionError exception and set result to None.
- <b>4-list_division.py</b>: Divide items in the first list by items in the second list. If they can't be divided then catch the corresponding exception, print a message, and set the result to 0.
- <b>5-raise_exception.py</b>: Raise a TypeError exception
- <b>6-raise_exception_msg.py</b>: Raise a NameError exception with a given message.
- <b>100-safe_print_integer_err.py</b>: Print a given value if it is an integer. If it's not an integer catch that exception and print the error message to stderr.
- <b>101-safe_function.py</b>: Run a given function with the given arguments. Catch any exceptions and print out their error messages to stderr.
- <b>102-magic_calculation.py</b>: Function recreated from given bytecodes

###Author
Corbin Coleman
